#!/usr/bin/env python
__description__ = \
"""
Still a hacked script.  Uses a nexus file to figure out the names of each 
sequence in a set of trees generated by a mrbayes run, then puts those names
into the tree file.
"""


import sys, re
from string import letters
from random import choice

f = open(sys.argv[1],'r')
lines = f.readlines()
f.close()

to_grab = ["GG","UU","EE","OU"]
counter = 1
out = []
for l in lines:
    if l[0:2] in to_grab:
        out.append((counter,"".join([choice(letters) for c in range(10)]),
                   l.split()[0]))
        counter += 1

out.sort(reverse=True)

f = open(sys.argv[2],'r')
line = f.read()
f.close()

for o in out:
    pattern = re.compile("%i" % o[0])
    line = re.sub(pattern,o[1],line)   

for o in out:
    pattern = re.compile(o[1])
    line = re.sub(pattern,o[2],line)   

   
print line 

