#!/usr/bin/env python

import argparse, os
from phylogenetics.homologs import load_homologset

def main():

    # ---------------------------------------------------
    # command-line arg parsing
    # ---------------------------------------------------

    parser = argparse.ArgumentParser(description="""
    Construct a multiple sequence alignment using MSAProbs
    """)

    # command line arguments
    parser.add_argument("-i", "--input",
            help="Input pickle file containing homologset.",
            type=str,
            required=True)

    parser.add_argument("-o", "--output",
            help="Filename to save pickled homologset.",
            type=str,
            required=True)

    parser.add_argument("--ids",
            help="List of HomologSet ids to remove from a given set.",
            nargs='+',
            type=str,
            default=True)

    # Parse the arguments
    args = parser.parse_args()

    # ---------------------------------------------------
    # Main code for removing homologs
    # ---------------------------------------------------

    # Open homologset and run msaprobs to align sequences.
    hs = load_homologset(args.input)

    # Remove homologs
    hs.rm_homologs(args.ids)

    # Write to homologset pickle
    hs.write(args.output, format="pickle")

if __name__ == "__main__":
    main()
