#!/usr/bin/env python

import argparse
from phylogenetics.homologs import load_homologset
from phylogenetics.msaprobs import run_msaprobs

def main():

    # ---------------------------------------------------
    # command-line arg parsing
    # ---------------------------------------------------

    parser = argparse.ArgumentParser(description="""
    Add an alignment to a homolog set.
    """)

    # command line arguments
    parser.add_argument("--homset",
        help="Input pickle file containing homologset.",
        type=str,
        required=True)

    parser.add_argument("--alignment",
        help="Alignment fasta file.",
        type=str,
        required=True)

    # Parse the arguments
    args = parser.parse_args()

    # ---------------------------------------------------
    # command-line arg parsing
    # ---------------------------------------------------

    # Open homologset
    hs = load_homologset(args.homset)

    # Add alignment to homologset
    hs2 = alignment_to_homologs(hs, args.alignment)

    # Write homologset to file
    hs2.write(args.output + ".pickle", format="pickle")

if __name__ == "__main__":
    main()
